//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektKomunikacja.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaints
    {
        public int IDComplaint { get; set; }
        public int OrderID { get; set; }
        public string Reason { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
