//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektKomunikacja.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Complaints = new HashSet<Complaints>();
        }
    
        public int OrderID { get; set; }
        public int ClientID { get; set; }
        public int employeeID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string ItemName { get; set; }
        public string ItemColor { get; set; }
        public Nullable<bool> Project { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaints> Complaints { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
